### ISSUE TITLE
Bootstrap classes

### ISSUE THREAD

**Issue by boryskuczkowski** [Radi85/Comment#1]
Hey there, thanks for a nice package,

Any way to actually change the bootstrap classes on elements or just local css tinkering?
(comment button's text overflows on certain resolutions and profile picture responsiveness is not gradual)

**Comment by Radi85** [comment]
Hello @boryskuczkowski , thanks for the feedback.
At the moment, styling can be overridden by local css only, however I will work on the templates so that the BS classes can be dynamically changed.

The profile pic is wrapped by `.col-2 and .col-md-1` BS classes so its size changes based on these classes. It would be appreciated to share your idea if you have a better way to implement this or feel free to contribute to the project. PRs are welcome :)

Finally, I retested the comment button on different resolutions and the text doesn't overflow. Attached screenshots for different resolutions before and right after the break points.

![320px](https://user-images.githubusercontent.com/25413382/46612699-9b964800-cb11-11e8-9828-36699a1c7706.png)
![575px](https://user-images.githubusercontent.com/25413382/46612700-9b964800-cb11-11e8-8511-33e0a378bc46.png)
![576px](https://user-images.githubusercontent.com/25413382/46612701-9c2ede80-cb11-11e8-87d2-bea5da2dd6ee.png)
![767px](https://user-images.githubusercontent.com/25413382/46612702-9c2ede80-cb11-11e8-9bfb-3ed82ecbf872.png)
![768px](https://user-images.githubusercontent.com/25413382/46612703-9c2ede80-cb11-11e8-8baa-70b56bc0caa9.png)

**Comment by boryskuczkowski** [comment]
![overflow](https://user-images.githubusercontent.com/37176465/46622144-698ce200-cb21-11e8-9ed1-8b063e2aa2d0.jpg)

Also I get this error when trying to delete post:
comment.js:13 Uncaught TypeError: $(...).modal is not a function
    at Object.beforeSend (comment.js:13)
    at Function.ajax (jquery-3.2.1.min.js:4)
    at HTMLButtonElement.loadForm (comment.js:7)
    at HTMLDocument.dispatch (jquery-3.2.1.min.js:3)
    at HTMLDocument.q.handle (jquery-3.2.1.min.js:3)


I assume its due to JQuery being already used by other widget, and it's the different version. I use full version of JQuery 3.3.1.js, so probably this is causing the problem although I haven't tried to test if having your slim version only will address the issue.

**Comment by boryskuczkowski** [comment]
Ok, so as far as jquery error is concerned, that's a conflict between two cdn versions. I removed the {{include static}} tag from template and copied comments.js file alone into static folder inside blog app then linked to using <script type="text/javascript" src="{% static 'blog/comment.js' %}"></script> in base.html.
Just don't include Jquery if you have one already.

**Comment by Radi85** [comment]
I just pushed a new branch Fix-jquery-and-btn-issues to fix the issues you listed above. 
static files must be included inside the base template and under your jquery, the {% include_static %} has only comment.js file without jquery for those who are using jquery alreay such as your case. User can now extend templates to override BS classes, this will give you more control on the comment look.

the example in this branch demonstrates the new changes.

The documentation will be updated soon.

**Comment by Radi85** [comment]
I will be waiting for your feedback to close this issue out.

**Comment by boryskuczkowski** [comment]
Hey, great effort.
{% include_static %} works as expected. I have one request, could you change this:
class="col-sm-3 col-md-2 **px-2** m-3 m-sm-0"
![pre](https://user-images.githubusercontent.com/37176465/46702550-77bf2900-cc1b-11e8-8ef1-270f443cf3f2.jpg)

to this:
class="col-sm-3 col-md-2 **px-0** m-3 m-sm-0"
![post](https://user-images.githubusercontent.com/37176465/46702633-bce35b00-cc1b-11e8-8b4b-1b63a9eab33e.jpg)

**Comment by Radi85** [comment]
The documentation has been updated. All the issues mentioned here are fixed now.
