### ISSUE TITLE
Toggling of follow button in javascript breaks replies when subscription is disabled

### ISSUE THREAD

**Issue by devmedtz** [Radi85/Comment#175]
### Environment
* python version = 3.9
* django Version = 3.1.1
* django-comments-dab = 2.6.0

### Describe the bug
I got a JS alert error "Unable to post your comment! please try again" when replying to a comment, after clicking the okay button the reply appended, while the form not clear

### Steps To Reproduce
1. Do not use the subscription option i.e. make sure `COMMENT_ALLOW_SUBSCRIPTION` is not set to `True`(which is the default behavior).
2. Try to reply to a comment.

### Expected behavior
The reply should submit without an error. 

### Screenshots
![Capture](https://user-images.githubusercontent.com/32010856/112448369-60c90e80-8d63-11eb-9918-2342b33f040c.PNG)

**Comment by abhiabhi94** [comment]
Till you can fill in the steps to reproduce, it would be liking shooting in the dark to figure out what exactly caused this behavior.

**Comment by abhiabhi94** [comment]
The library seems to be working fine on my end.

Until we can reproduce the issue at our end, I'm afraid we can't offer any help. Please list the steps to reproduce your issue. If you have any doubts regarding the setup of the application, please have a look at the [test application](https://github.com/radi85/comment/blob/develop/test/).

Also, please consider posting the output on the developer console of your browser when you get such an error.

**Comment by devmedtz** [comment]
The console is clear, not shown any error

**Comment by abhiabhi94** [comment]
Hey @devmedtz, open-source is not free tech support.

Unless you are paying someone, they don't have time to go to your website, register an account and do-stuff to solve your issue.
To reproduce the issue, either you can give me details of a dummy account on that website 
OR 
Please try to list the minimal steps that you have done after the installation of `django-comments-dab` so that the error that can be reproduced.

Even the repository link that you gave is having issues, when trying to create a superuser. You are probably using the method `normalize_username` at the wrong place in your code for creating user.

**Comment by abhiabhi94** [comment]
Hey @devmedtz, thanks for the issue report.

I have fixed this in the branch https://github.com/abhiabhi94/Comment/tree/fix/follow-js. Could you please use that branch to check and inform me it works on your end now?

**Comment by devmedtz** [comment]
> Hey @devmedtz, thanks for the issue report.
> 
> I have fixed this in the branch https://github.com/abhiabhi94/Comment/tree/fix/follow-js. Could you please use that branch to check and inform me it works on your end now?

It works now to my end, I put COMMENT_ALLOW_SUBSCRIPTION=False OR COMMENT_ALLOW_SUBSCRIPTION=True, Both work fine to my end, Thanks a lot, I really appreciate it.
