### ISSUE TITLE
Display comment count for object in the index page

### ISSUE THREAD

**Issue by bitFez** [Radi85/Comment#82]
Comments are working fine in the post pages but it would be great if we could display a comment count in the index page where posts are listed.

**Comment by abhiabhi94** [comment]
You may use the template tag `get_comments_count` by passing it the instance of the model associated and the user.

For e.g. inside the page where you have posts listed, you may use something like this

```jinja
{% load comment_tags %}
...
{% get_comments_count post user %}
...
``` 

Although the feature is implemented, it doesn't have documentation supporting it. If you have some time, it would be really great if you could consider making a pull request to add the documentation in the `README.rst` so that other developers too could benefit.

**Comment by learnICT** [comment]
Thank you I would definitely try to do that. I would love to contribute.
I'm really just a rookie though! haha

**Comment by abhiabhi94** [comment]
> I'm really just a rookie though! haha

No issues, We all started one day. In case you are interested in adding to the documentation and have any questions, we may continue the discussion here. All instructions are mentioned inside https://github.com/radi85/comment/tree/master/CONTRIBUTING.rst

Although, for documentation changes you don't necessarily need to set up development environment, you can directly [fork](https://docs.github.com/en/enterprise/2.20/user/github/getting-started-with-github/fork-a-repo) this repository and edit the file directly on GitHub and make a pull request from there.
